### ISSUE TITLE
 Bitte installieren Sie SDK: Gehen Sie zu Plugins/jtl_postfinancecheckout und führen Sie composer install aus

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#1]
Hallo

PHP 8.1.12
JTL Shop 5.2.2

Nach Installation gemäss Anleitung und ausführen von composer install sieht man im Terminal wie wallee/sdk installiert wird:

Lock file operations: 1 install, 0 updates, 0 removals
  - Locking wallee/sdk (3.2.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading wallee/sdk (3.2.0)
  - Installing wallee/sdk (3.2.0): Extracting archive
Generating autoload files

Im Backend kann danach das Plugin installiert werden.

Sobald man die geforderten Daten von Checkout abfüllt und speichert, erscheint folgende Fehlermeldung:

 "Bitte installieren Sie SDK: Gehen Sie zu Plugins/jtl_postfinancecheckout und führen Sie composer install aus"
 
 Ein erneutes ausführen von composer install führt zu keiner Veränderung.

Es sind keine neuen Zahlungsarten angelegt worden.

Bitte um Hinweise wie man das fixen kann.

Danke

**Comment by theodorspringwallee** [comment]
Dear [Alcpaone](https://github.com/Alcpaone)

Please can you share your issue with the PF Support and also please send your shop credentials, that they can check your issue individually: https://www.postfinance.ch/de/support/hotline.html

Best regards

**Comment by Alcpaone** [comment]
Hallo Herr Spring
Die PF ist seit letzter Woche schon informiert. Die Supportseite ist übrigens die falsche.
Korrekt wäre:
https://www.postfinance.ch/de/support/produkte/onlineshop-pos/kontakt-und-support-postfinance-checkout.html
wenn es die PF lösen soll.

Dann sind wir ja mal gespannt, ob das zum laufen kommt bevor PSP abgeschaltet wird.

Schönen Nachmittag

> Dear [Alcpaone](https://github.com/Alcpaone)
> 
> Please can you share your issue with the PF Support and also please send your shop credentials, that they can check your issue individually: https://www.postfinance.ch/de/support/hotline.html
> 
> Best regards
