### ISSUE TITLE
Error 500 if payment canceled (use of button Zahlung abbrechen)

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#10]
@thibault-mambour @edgaraswallee 

Plugin Version 1.0.**7**
Shop Version 5.2.4
PHP 8.1
Cache cleared

If payment canceled, **error 500** on return to the store. 

Displayed url: domainname.ch/postfinancecheckout-payment-failed

**Comment by thibault-mambour** [comment]
hi @Alcpaone , could you please run debug mode and share with us the error you get ?
you can do so by adding in config.JTL-Shop.ini.php
`ini_set(‘display_errors’, 1);`

**Comment by PAO1908CH** [comment]
with twint and cancel:

`Fatal error: Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, null given in /www/htdocs/w01af598/braun-service.ch/plugins/jtl_postfinancecheckout/frontend/postfinancecheckout_failed_payment.php:24 Stack trace: #0 /www/htdocs/w01af598/braun-service.ch/plugins/jtl_postfinancecheckout/frontend/postfinancecheckout_failed_payment.php(24): strtolower(NULL) #1 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Controller/PageController.php(280): include('/www/htdocs/w01...') #2 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Controller/PageController.php(233): JTL\Router\Controller\PageController->getPluginPage() #3 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Controller/DefaultController.php(114): JTL\Router\Controller\PageController->getResponse(Object(Laminas\Diactoros\ServerRequest), Array, Object(JTL\Smarty\JTLSmarty)) #4 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Strategy/SmartyStrategy.php(40): JTL\Router\Controller\DefaultController->getResponse(Object(Laminas\Diactoros\ServerRequest), Array, Object(JTL\Smarty\JTLSmarty)) #5 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Route.php(167): JTL\Router\Strategy\SmartyStrategy->invokeRouteCallable(Object(League\Route\Route), Object(Laminas\Diactoros\ServerRequest)) #6 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): League\Route\Route->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #7 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/PhpFileCheckMiddleware.php(36): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #8 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\PhpFileCheckMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #9 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/OptinMiddleware.php(49): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #10 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\OptinMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #11 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/CurrencyCheckMiddleware.php(26): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #12 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\CurrencyCheckMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #13 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/LocaleCheckMiddleware.php(34): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #14 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\LocaleCheckMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #15 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/CartcheckMiddleware.php(25): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #16 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\CartcheckMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #17 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/WishlistCheckMiddleware.php(24): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #18 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\WishlistCheckMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #19 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/SSLRedirectMiddleware.php(43): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #20 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\SSLRedirectMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #21 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/MaintenanceModeMiddleware.php(40): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #22 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\MaintenanceModeMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #23 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Middleware/LocaleRedirectMiddleware.php(38): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #24 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): JTL\Router\Middleware\LocaleRedirectMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #25 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Strategy/ApplicationStrategy.php(37): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #26 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(59): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(Laminas\Diactoros\ServerRequest), Object(League\Route\Dispatcher)) #27 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Dispatcher.php(53): League\Route\Dispatcher->handle(Object(Laminas\Diactoros\ServerRequest)) #28 /www/htdocs/w01af598/braun-service.ch/includes/vendor/league/route/src/Router.php(111): League\Route\Dispatcher->dispatchRequest(Object(Laminas\Diactoros\ServerRequest)) #29 /www/htdocs/w01af598/braun-service.ch/includes/src/Router/Router.php(677): League\Route\Router->dispatch(Object(Laminas\Diactoros\ServerRequest)) #30 /www/htdocs/w01af598/braun-service.ch/includes/src/Shop.php(472): JTL\Router\Router->dispatch(Object(JTL\Smarty\JTLSmarty)) #31 /www/htdocs/w01af598/braun-service.ch/index.php(7): JTL\Shop::dispatch() #32 {main} thrown in /www/htdocs/w01af598/braun-service.ch/plugins/jtl_postfinancecheckout/frontend/postfinancecheckout_failed_payment.php on line 24`

**Comment by thibault-mambour** [comment]
thank you @Alcpaone

**Comment by thibault-mambour** [comment]
hi @Alcpaone @PAO1908CH the latest release should tackle this issue. Could you please double check ?
