### ISSUE TITLE
With plugin 1.08 payments are not synchronized to WAWI

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#12]
We got a order right now, payment with twint, in checkout backend the payment has been successfull:
![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/37312ac5-cc87-4e36-abf0-42e8e3f0bdbc)

The order has been created in the shop and it is also synchronized to the shop, but it is not marked as paid in WAWI and also not in shop:
![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/e94ba6bb-0c79-495e-83ca-1bd268d2afd2)

Regards

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , thank you for the feedback, we will have a look

**Comment by thibault-mambour** [comment]
@PAO1908CH , this only happens with twint or same with credit card ?

**Comment by PAO1908CH** [comment]
Unfortunately I can not test that at the moment 

> @PAO1908CH , this only happens with twint or same with credit card ?

It happens also with Credit Card, tested right now.

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , could you please confirm if with the latest release this issue is solved ?

**Comment by PAO1908CH** [comment]
Negative, with 1.10 payments are still not synchronized from Plugin to the shop and as it is not set as paid in the shop, it's also not set as paid in the wawi. I think the problem is with the interface Plugin => Shop, where the payment is not set as received, as when I check the orders in shop backend, the order is here, but not marked as paid.

**Comment by edgaraswallee** [comment]
Hello @PAO1908CH , 

I'm thinking why this issue still exists. Perhaps there are several ways to mark a payment as completed? Could you make a video demonstrating the issue, or would you be available for a video call? I would like to reproduce it and fix it.

**Comment by PAO1908CH** [comment]
Sure, Im here till 1800 CET.
Do you want to Call me today?
Regards

edgaraswallee ***@***.***> schrieb am Fr., 22. Dez. 2023,
16:03:

**Comment by edgaraswallee** [comment]
Let's meet 1720 CET here?

https://meet.google.com/uts-sqck-nxr?authuser=0

**Comment by edgaraswallee** [comment]
@PAO1908CH maybe are you available right now for a call?

**Comment by PAO1908CH** [comment]
yes, +41763875055

**Comment by edgaraswallee** [comment]
https://meet.google.com/ohw-vqdu-bdp?authuser=0

**Comment by edgaraswallee** [comment]
Hello, @PAO1908CH , new release has been made, can you please check if you issues are fixed?
