### ISSUE TITLE
Webhook Aufruf Fehlgeschlagen / looks like orders don't will send to JTL WAWI when this happens

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#13]
Since Plugin Version 1.0.10 we get this messages from PF.
JTL Shop 5.2.4
PHP 8.1

no specific time or action from our part. We don’t know what is triggering this messages. Most we get a few of them in a row.

here the details from the PF Backend:

``HTTP/1.1 500 Internal Server Error
x-ua-compatible: IE=edge
expires: Thu, 19 Nov 1981 08:52:00 GMT
Server: nginx
x-frame-options: SAMEORIGIN
Connection: keep-alive
x-turbo-charged-by: LiteSpeed
pragma: no-cache
Date: Sat, 23 Dec 2023 19:41:22 GMT
set-cookie: JTLSHOP=XXXXXXXXXXXXXXXX; path=/; secure; HttpOnly
x-content-type-options: nosniff
cache-control: no-store, no-cache, must-revalidate
Content-Length: 0
Content-Type: text/html; charset=utf-8

And this text is in the PF Backend (xxxxxx was a number that I can provide if necessary by a secure channel):

Der Webhook Aufruf '[Webhook Invocation: (https://checkout.postfinance.ch/s/xxxxxx/webhook/invocation/view/265544216)' schlugfehl, weil der Aufruf der URL wiederholt mit einem Fehler beantwortet wurde.

**Comment by Alcpaone** [comment]
This morning we got until now 32 emails, starting at 06:45 am until 8:55 am. So it starting to be annoying..

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 

**PSP Shutdown in 3 days!** and we have to migrate our system to a new version before we can use your plugin. So please hurry up! Thank you

**Comment by thibault-mambour** [comment]
hi @Alcpaone , can you please send all the above to the support with all the information ? It should help us find what might be going wrong

**Comment by Alcpaone** [comment]
@thibault-mambour thank you but there is no more information to send to you.

Here a other message from the checkout Backend (XXXXXXXX was the cookie):

HTTP/1.1 500 Internal Server Error
x-ua-compatible: IE=edge
expires: Thu, 19 Nov 1981 08:52:00 GMT
Server: nginx
x-frame-options: SAMEORIGIN
Connection: keep-alive
x-turbo-charged-by: LiteSpeed
pragma: no-cache
Date: Sat, 23 Dec 2023 19:41:22 GMT
set-cookie: JTLSHOP=XXXXXXXXXXX; path=/; secure; HttpOnly
x-content-type-options: nosniff
cache-control: no-store, no-cache, must-revalidate
Content-Length: 0
Content-Type: text/html; charset=utf-8


**PSP Shutdown in 2 days!**

**Comment by Alcpaone** [comment]
@thibault-mambour we keep getting this messages. A decision is to make. We don’t know what we have to choose…
Options are:

Webhook Erneut Senden | Webhook Listener deaktivieren | Fehlermeldung ignorieren 

error message:
HTTP/1.1 500 Internal Server Error
x-ua-compatible: IE=edge
expires: Thu, 19 Nov 1981 08:52:00 GMT
Server: nginx
x-frame-options: SAMEORIGIN
Connection: keep-alive
x-turbo-charged-by: LiteSpeed
pragma: no-cache
Date: Sun, 31 Dec 2023 08:03:32 GMT
set-cookie: JTLSHOP=mcnuhtq7af8otii7n98b8sqbfs; path=/; domain=.domainname.ch; secure; HttpOnly
x-content-type-options: nosniff
cache-control: no-store, no-cache, must-revalidate
Content-Length: 0
Content-Type: text/html; charset=utf-8

**Comment by Alcpaone** [comment]
@thibault-mambour 

happy new year!

Here some update to this issue. There is no specific time and we can't see any connection to orders.

<img width="285" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/61f6ec88-0b67-4577-8c7f-0184511152df">

**Comment by Alcpaone** [comment]
@thibault-mambour this is what we can see on the checkout system, looks like we loose orders.
and we still don't know why this is happening. What do you need to resolve this urgend issue?

<img width="449" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/302b5c44-1389-4f0c-b14b-3ed174c8bfb5">

**Comment by Alcpaone** [comment]
we just used now "webhook erneut senden" and got a bunch of orders in our system, some of them are 4 days old! No problem for today as everthing was closed for public holidays. Any way you can show that you are working on that issue please?

**Comment by thibault-mambour** [comment]
hi @Alcpaone we are currently working on enabling partial refunds. 
After that we will look at the different issues you opened (we are looking at what is possibly going wrong for this specific case with our support team)

**Comment by thibault-mambour** [comment]
hi @Alcpaone , do you think you could set your debug mode to on and trigger one failed webhook again ? This would greatly help us understand where the problem might lie.

To do so:

In file includes/config.JTL-Shop.ini.php:
ini_set(‘display_errors’, 1);|
need to replace from 0 to 1 (to enable)

**Comment by Alcpaone** [comment]
> hi @Alcpaone we are currently working on enabling partial refunds. After that we will look at the different issues you opened (we are looking at what is possibly going wrong for this specific case with our support team)

Thank you for your answer. If you would ask me, i would set a lower prio to the mentioned task. Why? Because refund can be done in the checkout backend without any problem (workaround ok). I would suggest to set higher prio to basic funtions of the plugin like PHP Errors. Just my 2 cents..

<img width="877" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/3032e722-3aed-496d-961d-0cdfec04f425">

**Comment by Alcpaone** [comment]
> hi @Alcpaone , do you think you could set your debug mode to on and trigger one failed webhook again ? This would greatly help us understand where the problem might lie.
> 
> To do so:
> 
> In file includes/config.JTL-Shop.ini.php: ini_set(‘display_errors’, 1);| need to replace from 0 to 1 (to enable)

I will do that and also add some PHP Error Log. If you need anything else let me know or ask please Patricius from your comnpany. He has all Logins to our Backend and also to the Server.

thank you

**Comment by Alcpaone** [comment]
@thibault-mambour here our email trafic from the Postfinance backend to us from the last 8 houres..

<img width="748" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/7dc4ca7a-c221-4be3-9889-a3e32bbcfeaf">

**Comment by Alcpaone** [comment]
> hi @Alcpaone , do you think you could set your debug mode to on and trigger one failed webhook again ? This would greatly help us understand where the problem might lie.
> 
> To do so:
> 
> In file includes/config.JTL-Shop.ini.php: ini_set(‘display_errors’, 1);| need to replace from 0 to 1 (to enable)

Good Morning @thibault-mambour 

Done what you asked for but there is nothing to see in the frontend (display errors enabled) when I manuelly click on the hook with time out in the postfinance backend. There is only a message in red, that the server didnt respond as expectet. See picutre below:

<img width="583" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/d89d116a-7ea2-4dba-9b61-6ac685c1c6bf">

In the php Error log i can see this:
#35 {main}
  thrown in /path removed/includes/src/Plugin/Payment/Method.php on line 97
[04-Jan-2024 09:07:56 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: JTL\Plugin\Payment\Method::__construct(): Argument #1 ($moduleID) must be of type string, null given, called in /path removed/plugins/jtl_postfinancecheckout/Webhooks/Strategies/PostFinanceCheckoutNameOrderUpdateTransaction
Strategy.php on line 83 and defined in /path removed/includes/src/Plugin/Payment/Method.php:97

Looks like it is a problem between Checkout Backend Communication an the plugin. Please rise this issue in priority to high. Thank you

**Comment by thibault-mambour** [comment]
hi @Alcpaone , this error should be fixed with the next release. I cannot give you a sure time (we are still checking few things) but we hope to be released tomorrow

**Comment by Alcpaone** [comment]
> hi @Alcpaone , this error should be fixed with the next release. I cannot give you a sure time (we are still checking few things) but we hope to be released tomorrow

I would prefer, you do the release asap, not tomorrow. Look for example at this history here. We are loosing orders. I have done a chat with one of them. Theyx say ther pay button isnt working!

<img width="286" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/8653c4c3-8bea-4bd7-a306-b2054cba150c">

**Comment by Alcpaone** [comment]
@thibault-mambour i got now a screenshot from a customer. The button bezahlen is not clickable.

<img width="398" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/519a2335-9001-4b50-9d5f-63c04e20e13b">

**Comment by Alcpaone** [comment]
> hi @Alcpaone , we made the release for a fix, do you think it would be possible to confirm if it fix the problem ?

Plugin updated. We will have to wait for the next customer (i will test anyway). Will send you Informations asap. Thank you!

**Comment by Alcpaone** [comment]
@thibault-mambour Payments until now are working what we can see in the Checkout backend with 1.0.14
I used a old webhook message in the postfinance backend (just the newest), used resend and got a successfull message. First time this works. Concrats! At the moment, it looks like Version 1.0.14 was a good move. So i hope the Mailbox tomorrow morning isnt again full with webhook messages.

We have send now to several customers that payment didnt work the last few days, some email informations like "please try again, should work now". I will update you tomorrow.

**Comment by Alcpaone** [comment]
@thibault-mambour well done! until now no more webhook Messages! Looks like this Problem is solved. Thank you
