### ISSUE TITLE
Urgent: payments over 1000 are divided by 100

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#14]
If cart has a value over 1000 CHF the amount that is charged to the customer card is divided by 100 so basically only 10 CHF are charged...

That's a very very big issue.

@andrewrowanwallee
@edgaraswallee
@sauliususoniswallee

**Comment by Alcpaone** [comment]
OMG!!!

@PAO1908CH thank you so much for finding and reporting this issue!

**Comment by edgaraswallee** [comment]
Hello, thanks for letting us know about such issue. I have made a release 1.0.12 with a hotfix for it.

**Comment by Alcpaone** [comment]
@edgaraswallee thank you for the hot fix. After transfer no updat is visible in the backend. Shows still 1.0.11
