### ISSUE TITLE
1.0.14: DECLINE/VOIDED/FAILED leads to Type Error

### ISSUE THREAD

**Issue by t-oster** [pfpayments/jtl-5#19]
Hi,

in 1.0.14 you added the following lines to PostFinanceCheckoutNameOrderUpdateTransactionStrategy.php:
```
$moduleId = new Method($paymentMethodEntity->cModulId) ?? '';
$paymentMethod = new Method($moduleId);
```
which leads to a TypeError, because the new Method constuctor takes a String and if cModulId is not empty you save a method to $moduleId instead of the ID.

I think it should be
```
$moduleId = $paymentMethodEntity->cModulId) ?? '';
$paymentMethod = new Method($moduleId);
```
but no idea if calling new Method with an empty module ID makes any sense.

Here is the stack trace:
```
05-Jan-2024 11:47:15 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: JTL\Plugin\Payment\Method::__construct(): Argument #1 ($moduleID) must be of type string, JTL\Plugin\Payment\Method given, called in /var/www/html/plugins/jtl_postfinancecheckout/Webhooks/Strategies/PostFinanceCheckoutNameOrderUpdateTransactionStrategy.php on line 85 and defined in /var/www/html/includes/src/Plugin/Payment/Method.php:97
Stack trace:
#0 /var/www/html/plugins/jtl_postfinancecheckout/Webhooks/Strategies/PostFinanceCheckoutNameOrderUpdateTransactionStrategy.php(85): JTL\Plugin\Payment\Method->__construct(Object(JTL\Plugin\Payment\Method))
#1 /var/www/html/plugins/jtl_postfinancecheckout/Webhooks/PostFinanceCheckoutOrderUpdater.php(34): Plugin\jtl_postfinancecheckout\Webhooks\Strategies\PostFinanceCheckoutNameOrderUpdateTransactionStrategy->updateOrderStatus('176881251')
#2 /var/www/html/plugins/jtl_postfinancecheckout/Webhooks/PostFinanceCheckoutWebhookManager.php(76): Plugin\jtl_postfinancecheckout\Webhooks\PostFinanceCheckoutOrderUpdater->updateOrderStatus('176881251')
#3 /var/www/html/plugins/jtl_postfinancecheckout/frontend/postfinancecheckout_webhook.php(7): Plugin\jtl_postfinancecheckout\Webhooks\PostFinanceCheckoutWebhookManager->listenForWebhooks()
#4 /var/www/html/includes/src/Router/Controller/PageController.php(280): include('/var/www/html/p...')
....
```

**Comment by thibault-mambour** [comment]
hi @t-oster , thank you for bringing this to us. Does it impact the customer journey directly ?

**Comment by t-oster** [comment]
I am not sure. As far as I can interpret the process, this occurs when the webservice tries to sync the failed state to the JTL Shop, which does not occur because of PHP exploding on the type error. So the impact would be that the payment hangs in pending while it is cancelled in reality.

And of cause tons of error logs.

**Comment by Alcpaone** [comment]
@t-oster what do you mean with hanging? On the payment form or in the checkout backend? I'm asking because we see a lot of orders in the checkout backend that rest a long time on the state "ausstehend". After a while they change to "Fehlgeschlagen".

**Comment by t-oster** [comment]
I would think in the backend, because as far as I can see this happens on the sync between postfinance and the JTL shop which seem to happen in the background.

**Comment by Alcpaone** [comment]
@thibault-mambour any updates here?

**Comment by t-oster** [comment]
As far as I can see in the file https://github.com/pfpayments/jtl-5/blob/09be5db96661566a471eb3aebf7381ad2850d23b/Webhooks/Strategies/PostFinanceCheckoutNameOrderUpdateTransactionStrategy.php#L85 it looks fixed
