### ISSUE TITLE
Orders are placed even then when payment was not successfull

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#2]
I installed Version 1.04 of your plugin. As soon as I proceed to checkout, choose a payment method, continue and cancel the payment, I'm sent back to the cart. But, everytime a order is generated in JTL Shop, ofcourse without payment, but the order is here and the products are reserved and the customer gets each time a order confirmation. 

So I think it should be like that:

- Customer proceeds to the payment
- Payment is aborted or rejected
=> Customer comes back to his basket and no order is placed in JTL Shop.

Kind regards

**Comment by PAO1908CH** [comment]
Additional info: Customer gets also each time he tries to pay a order confirmation email, even when the order was not finalized or paid.

**Comment by theodorspringwallee** [comment]
Dear [PAO1908CH](https://github.com/PAO1908CH)

Thank you for your explanations. We will check this on our side.

Best regards

**Comment by PAO1908CH** [comment]
With payment plugin 1.05 this problem has been fixed, thank you!

**Comment by Alcpaone** [comment]
> With payment plugin 1.05 this problem has been fixed, thank you!

No, with our installation the issue is still here. It isn't fixed with 1.05

JTL Shop 5.2.4
PHP 8.1
let me know if you need anything else to fix this asap please.

**Comment by PAO1908CH** [comment]
Which problem? The Mails or the order created even when the payment was not
successfull?

Alcpaone ***@***.***> schrieb am Do., 14. Dez. 2023, 16:54:

**Comment by Alcpaone** [comment]
unpaid order is created even when the payment was not succesfull or goes back to change payment method. so we get a unpaid order in the Wawi.

**Comment by thibault-mambour** [comment]
hi @Alcpaone , we are working on wawi in a different ticket. We will inform you as soon as it is done.

**Comment by PAO1908CH** [comment]
Ensure that you have activated in all postfinance payment Methods, in jtl
shop backend, payment before order is Set to yes.

Alcpaone ***@***.***> schrieb am Do., 14. Dez. 2023, 17:21:

**Comment by PAO1908CH** [comment]
Affirm, that's the one I mean.

Alcpaone ***@***.***> schrieb am Do., 14. Dez. 2023, 19:20:

**Comment by Alcpaone** [comment]
@PAO1908CH looks like this option is working so we don't get unpaid orders. Please add this information to the documentation.

**Comment by PAO1908CH** [comment]
Im not developer 🤣 only a User like you.

Alcpaone ***@***.***> schrieb am Fr., 15. Dez. 2023, 13:26:

**Comment by Alcpaone** [comment]
looks like you @PAO1908CH know more then them!  Im not shure if I should laugh or cry about this fact 🤣🤣🤣

**Comment by thibault-mambour** [comment]
hi @Alcpaone , sure, we will update the documentation accordingly
