### ISSUE TITLE
Vouchers are added instead of deducted!

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#20]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee

If a customer uses a voucher code that should reduce the price, **instead the price raises for the amount of the voucher value.**

Example: If a customer uses a 10% discount code, the price is not reduced but increased by 10%.

We currently have many codes in circulation because we have written to all customers who have payment problems (unfortunately there are many) and now not even one voucher can be processed correctly by the plugin. Version 1.0.14

Please give us feedback on what you need to check and fix this asap.

**Comment by thibault-mambour** [comment]
hi @Alcpaone , where is the price being increased ? before the checkout, at the checkout or during the payment ?

**Comment by Alcpaone** [comment]
@thibault-mambour the price is increased during the payment. Cart says CHF 19.70, TWINT form shows CHF 24.09

Product Price CHF 21.90
Discount 10% CHF 2.19
VAT 8.1% CHF 1.48 inluded
Total Payment CHF 19.40

Postfinance Checkout TWINT shows QR Code and Price to pay: CHF 24.09

So the discount is added to the price. CHF 21.90+2.19 = CHF 24.09

**Comment by Alcpaone** [comment]
> hi @Alcpaone , we managed to reproduce the issue, we are looking into it

ok, thank you. When can we expect an update?

ps: please add such a basic function to your standard checks before releasing products in the future. after all, this is not free software. we pay fees per transaction to Postfinance and at the moment we pay double because we have to send money back to customers that paid to much.

**Comment by thibault-mambour** [comment]
we expect it to be released today

**Comment by thibault-mambour** [comment]
hi @Alcpaone , the release was done, could you please confirm if it is fixing your problem ?

**Comment by Alcpaone** [comment]
@thibault-mambour done a few tests. Works now with Release 1.0.15 . Thank you! 

There is always a price difference of 1 to 2 cents that the customer has to pay. I'm not shure where that comes from. 

Example: Price in Cart: CHF 21.0**5** -> Posfinance Checkout CHF 21.0**6**

Not problem for us. Just for your information.

**Comment by thibault-mambour** [comment]
hi @Alcpaone , thank you for the feedback !
Regarding this difference, we had another merchant that reported this discrepancy but they told us it was probably a shop misconfiguration and managed to fix it. With the plugin we are taking the amount that is sent by JTL. 
If this wouldn't be the case for you, we are happy to look into it.

**Comment by Alcpaone** [comment]
@thibault-mambour mmh, ok. good to know, that the plugin is not adding anything. Thank you.
I will search for any options in the shop regarding this setting, but as mentioned before this isn't a big issue for the moment.

**Comment by Alcpaone** [comment]
@thibault-mambour can you please ask the other merchant what they did change? Thank you
