### ISSUE TITLE
CRITICAL: Customer credit in the shopping cart is not transferred to Postfinance Checkout

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#21]
@thibault-mambour 

If the customer has a credit balance for payment in the store, this is taken into account in the store and displayed correctly, but the credit balance is ignored when billing in Postfinance Checkout. The information is therefore not taken over by the plugin.

if customers use credit, in the shop it shows product price less credit equals purchase price. 
Postfinance Checkout price is still normal price without credit discount.

**Comment by thibault-mambour** [comment]
hi @Alcpaone , how do you track on your store the customer credit ?

**Comment by Alcpaone** [comment]
@thibault-mambour we can track the customer credit (add / remove) in the WaWi that transfers all informations to the online shop. Since a while there is a bug so we have to check the actual balance for customers direct in the Shop DB. Why are your asking?

**Comment by thibault-mambour** [comment]
Hi @Alcpaone , I am asking because this wasn't a feature we had on our roadmap for the first delivery of the plugin. 
As we are keen to have the most complete plugin, we are trying to understand this use case.

**Comment by Alcpaone** [comment]
@thibault-mambour 
ok, I understand. Take a look here 
https://guide.jtl-software.com/jtl-wawi/kunden/guthaben-fuer-onlineshop-erhoehen/

**Comment by 3d-printerstore** [comment]
@thibault-mambour
We have the same problem
It's almost like the problem the plugin had with discounts, which were added. Now the credit a customer might have in his account is not deducted in the sum which is transferred to the payment method, but the credit-amount is deducted from his shop account.

**Comment by Alcpaone** [comment]
Hi @thibault-mambour

important: we are not talking about a classic voucher from the store, with e.g. 10% or a value of CHF 10.

We are talking about credits that the customer has received because for some reason (currently mostly due to plugin errors) we credit the customer with a CHF amount to his customer account in the online store. This is a standard function of JTL WAWI.

The customer sees this amount in his customer account as a credit and can use it when shopping. With Powerpay but ALSO with all other like TWINT etc. this amount is simply ignored.

Here you can see how to create such a credit note. This is then synchronized in the online store.

https://guide.jtl-software.com/jtl-wawi/verkauf/gutschrift-anlegen/

**Comment by 3d-printerstore** [comment]
Hi

I think that example below is better, as the "Gutschrift-Anlegen" hasn't got much to do with the credit amount which is transferred to the customers JTL Shop account.
https://guide.jtl-software.com/jtl-wawi/kunden/guthaben-fuer-onlineshop-erhoehen/

**Comment by Alcpaone** [comment]
Wie es hier aus? Wann können wir mit einer Version rechnen die diese Basisfunktion im Griff hat? Aktuell generiert es Mehraufwand (Kommunikation mit Kunden) und Mehrkosten (Gutschriften sind Kostenpflichtig).

**Comment by 3d-printerstore** [comment]
Yep , still no change - it' an awful lot of work giving all those credits back, because the customer sees the wrong amount he should pay!! Because it's not only that the credit amount isn't deducted, this amount is as well gone from the customers account, when the customer stops in the middle of the payment process!

**Comment by 3d-printerstore** [comment]
@edgaraswallee 
Could it be that someone has taken the wrong database column / variable?
I think that the total amount which should be transferred to the payment page is called "fGesamtsumme", but as far as I can see, the "fBetrag" is handed over as the "AuthorizedAmount" or the "incomingPayment"
I might of course be very wrong, as I'm nowhere near a specialist, but maybe it's worthwhile for you to look into it?

**Comment by Alcpaone** [comment]
@thibault-mambour @edgaraswallee  

It is working since 1.0.23 but we miss a few bucks if customers use credits!
Example: 
Cart value CHF 105.35
Credit CHF 27.73
so Customer should be charged  CHF 77.62
instead customer is charged with 75.50 in checkout.
so we miss in this case CHF 2.14

Can you please check your calculations in the plugin?

We don't use any plugins that change anything in the checkout

How is this possible? Why is this possible? We loose double now. First we offer credit because the plugin was such a bad product at the beginning and now we also don't charge enough for the cart 🤦‍♂️💩

Please fix this yesterday 😉

**Comment by Alcpaone** [comment]
looks good with 1.0.24 👍Thank you!
