### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by 3d-printerstore** [pfpayments/jtl-5#23]
Hi there
Have you added the recognition of a Thousands separator as well? 
Because we would like to use the Single quotation mark '   as the separator as used in Switzerland.
But if we'd leave it in the currencies, the problem with the divided payment price by 1000 would appear again.
Br's
Ralph

**Comment by thibault-mambour** [comment]
hi @3d-printerstore , in the latest release (1.0.16), we are supporting all separators.

**Comment by 3d-printerstore** [comment]
Thank you for this info
