### ISSUE TITLE
order numbers are incremented even if no successful payment is triggered.

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#24]
If a customer attempts to pay and then cancels the payment, the internal order number of the shop and checkout.postfinance will still be incremented. Although no order is written to the shop, there are still order numbers that do not actually exist and there are gaps in the number sequence.

![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/b6d3dcf3-0b7c-40e0-81d0-f4d5d11d6cc0)

You can see it above. 42065 was successfull, then one customer tried 7 times to pay, and each time it was not successfull, so the shop generated order numbers, without generating the order, what is what we want, but, next successfull order, that has come with order 42073, normally should be 42066.

Regards

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , you see the number being incremented because from our perspective, each tentative payment is a transaction, hence increasing the order number. 
Maybe you could provide us how is this impacting your operations ?

**Comment by PAO1908CH** [comment]
It is not directly impacting our operations, but there is a gap in the order numbering and it could be a problem if we need to debug other problems. That's the reason I think why in the old system, they had a completely other number. The problem there was that you were not able with a easy way to which order the payment correspond. So, it's not that important, let it on standby and let's wait what others say. If nobody else is complaining, you can leave it as it is.
Thanks a lot and kind regards

**Comment by Alcpaone** [comment]
@PAO1908CH done? if so, please close the issue so we can all see the remaining tasks. Thank you!
