### ISSUE TITLE
CRITICAL: voucher information will not be send to Powerpay

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#29]
If a customer uses invoice (powerpay), then a voucher will not be deductet from the total amount transfered to powerpay.
The customer has at the shop checkout let say CHF 100 - CHF 15 voucher, has to pay CHF 85. Powerpay sends email to customer that CHF 100 are to pay.

This is critical. Please check that asap!

I will send screenshots to Patricius. Ask him please if you need to see the problem like a customer.

**Comment by Alcpaone** [comment]
and also the order is send wrong to JTL Wawi (Example from before -> CHF 100 instead of CHF 85. 
In the order also no voucher visible, like it was send to Powerpay.

Please fix this asap.

**Comment by thibault-mambour** [comment]
hi @Alcpaone , we will link with patricius to see how we can handle it

**Comment by Alcpaone** [comment]
@thibault-mambour any news here? When will be the next release to fix such critical errors?

**Comment by thibault-mambour** [comment]
hi @Alcpaone , next week we will look to fix those issues

**Comment by Alcpaone** [comment]
@thibault-mambour next week? I think such basic functions should be fixed faster. This error burdens customers, dealers and service providers.

**Comment by martinreal91** [comment]
Same problem for us, the voucher amount is not getting deducted properly, when can we expect a fix for this critical issue?

**Comment by Alcpaone** [comment]
@thibault-mambour it is next week since yesterday 😉

**Comment by thibault-mambour** [comment]
hi @Alcpaone, sorry for the delay, we are currently working on fixing https://github.com/pfpayments/jtl-5/issues/33 and this story will be the next one

**Comment by Alcpaone** [comment]
@thibault-mambour i understand, that more languages are important but to be clear: basic functionality has in my opinion always highest priority as actual browser also translate languages but can’t fix plugin errors.

**Comment by martinreal91** [comment]
Hi @thibault-mambour is there any update on this topic? Do you already have a planned date for this fix?

**Comment by thibault-mambour** [comment]
hi @martinreal91 @Alcpaone , using the jtl plugin for voucher, we are able to use voucher. Could you provide the reproduction steps you are using ?

**Comment by martinreal91** [comment]
Hi @thibault-mambour it looks like it works now, after applying the voucher it seems to work properly.

**Comment by Alcpaone** [comment]
> hi @martinreal91 @Alcpaone , using the jtl plugin for voucher, we are able to use voucher. Could you provide the reproduction steps you are using ?

Hi @thibault-mambour

important: we are not talking about a classic voucher from the store, with e.g. 10% or a value of CHF 10.

We are talking about credits that the customer has received because for some reason (currently mostly due to plugin errors) we credit the customer with a CHF amount to his customer account in the online store. This is a standard function of JTL WAWI. 

The customer sees this amount in his customer account as a credit and can use it when shopping. With Powerpay but ALSO with all other like TWINT etc. this amount is simply ignored.

Here you can see how to create such a credit note. This is then synchronized in the online store.

https://guide.jtl-software.com/jtl-wawi/verkauf/gutschrift-anlegen/

**Comment by Alcpaone** [comment]
#21 is the same. I close this one so you can focus on #21
