### ISSUE TITLE
Proceed / Cancel button not viewable when choosing credit card payment

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#3]
When you proceed to payment, and you choose Credit Card:
![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/c3c3f69f-ad7e-4ae1-a53a-56e5946c0e52)

Then, as soon as the page with the card details shows up, you can not see the proceed/confirm or cancel buttons:

![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/73157269-722a-420c-b732-cd204a8a20c2)

Tested with version 1.05.

Only credit cards are affected, TWINT, Postfinance card works.

**Comment by thibault-wallee** [comment]
Hi @PAO1908CH , thank you for reporting this, our developers will have a look.

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , the release of today should fix the problem, could you please confirm ?

**Comment by PAO1908CH** [comment]
Hello again
Tried it out. Problem now is, that credt card option doesn't apear at all at checkout. But the payment method has been synchronized, so I can see it in the payments avaiable in the backend. One thing I saw:

the payment type Postfinance Card, has wrong description:
Pay conveniently with your credit or debit card.

But if you choose it, Postfinance Card payment apears. Maybe there is somewhere a mismatch between postfinance card and Credit card payments. Thererefore, I can not confirm at this stage, that the problem is away, as I can not test it...

Regards

**Comment by PAO1908CH** [comment]
Disregard, I unistalled everything and installed it again, it works! The only thing that remains is the wrong description of the Postfinance Card payment, but this can be solved by changing the payment name in the backend of the shop.

**Comment by PAO1908CH** [comment]
Cancel button is not avaiable if you are at the form where you can enter your credit card data. only proceed button is avaiable, no cancel payment button.

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 

**PSP Shutdown in 3 days!** and we have to migrate our system to a new version before we can use your plugin. So please hurry up! Thank you

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee

**PSP Shutdown in 2 days!** No news?

**Comment by Alcpaone** [comment]
@PAO1908CH done? if so, please close the issue so we can all see the remaining tasks. Thank you!
