### ISSUE TITLE
House Number not transfered to Postfinance Checkout

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#32]
Postfinande receives a lot of informations for each payment process.

It looks like the House number isn't send to Postfinance Checkout.
Email that will be send to customer from Postfinance Checkout don't show the House Number.
Customers write or call us because they think they have not entered the house number.

ALSO the Informations transfered to Powerpay are without House number. They have to send the invoices
on request as a letter by post, so the house number is necessary.

Please fix this asap.

Here the Informations that the Postfinance Checkout receives (send to us from Postfinance Support):

X = removed informations that where transfered correct.

"billingAddress": {
        "city": "XXXXXXXXX",
        "commercialRegisterNumber": null,
        "country": "CH",
        "dateOfBirth": "XXXX-XX-XX",
        "dependentLocality": null,
        "emailAddress": "[XXXXXX@XXXX.ch](mailto:XXXXXX@XXXXX.ch)",
        "familyName": "XXXXXXX",
        "gender": "MALE",
        "givenName": "XXXXXX",
        "legalOrganizationForm": null,
        "mobilePhoneNumber": null,
        "organizationName": "",
        "phoneNumber": "+XXXXXXXXX",
        "postalState": null,
        "postcode": "XXXX",
        "postCode": "XXXX",
        "salesTaxNumber": null,
        "salutation": "",
        "socialSecurityNumber": null,
        "sortingCode": null,
        "street": "XXXXXXXXXXXXX"
    },
    
    btw: salution also should not be empty.

**Comment by Alcpaone** [comment]
@thibault-mambour any news here? When will be the next release to fix such simple but crucial errors?

**Comment by 3d-printerstore** [comment]
@Alcpaone 
Do you have no problems with PowerPay? 
We can't differ between a normal B2B customer who is allowed to buy with normal invoice or a B2C customer who has chosen PowerPay, as both come in to the Wawi with payment method "invoice". Both orders would be of course sent to the WMS and be sent out. Not what I really want though and very time intense to monitor.
Actually since yesterday, those PowerPay come in without a payment method, but only with "Kauf auf Rechnung" in the order remarks - very strange and wrong

**Comment by Alcpaone** [comment]
@3d-printerstore if I understand you correct, I would say your setup of Versandarten isn't correct in your webshop.

und damit es schneller geht auf Deutsch: in den Versandarten definiert man WER diese nutzen kann. Dort kannst du unterscheiden zwischen den Gruppenzugehörigkeiten des Kunden.

<img width="82" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/26a2bb3b-48fd-473a-baa0-fbd0102205b4">


Mach also eine Versandart für B2B Kunde (Kunden muss zu dieser Gruppe gehören) und zeige ihm das an was DU möchtest an Zahlungsarten.

Mach eine zweite Versandart für B2C Kunden (Kunde muss zu dieser Gruppe gehören) und zeige ihm das an an Zahlungsarten was DU möchtest.

PS: aktuelle Probleme mit Powerpay -> Vorautorisierung funktioniert nicht (jeder Kunde sieht Powerpay auch wenn Bonität nicht ok ist) UND die Adresse wird unvollständig an Checkout und somit an Powerpay weiter gegeben (ohne Hausnummer). Absolut peinlich, da wurde **null getestet** bei WALLE. Keine Ahnung wie die arbeiten aber etwas ist da mehr komisch.

**Comment by 3d-printerstore** [comment]
@Alcpaone 
Nein, die Kundengruppenzugehörigkeit ist schon ok so, nur wird die falsche Zahlungsart von PostFinance übermittelt und zwar "Rechnung" und wenn du diese Zahlungsart aber schon hast, dann gibt es Probleme. Die übermittelte Zahlungsart sollte "Kauf auf Rechnung" sein und genau das kann ich bei der PostFinance nicht ändern - oder kannst du das?.

**Comment by Alcpaone** [comment]
@3d-printerstore prüf mal in der Wawi Zahlungen / Zahlungsarten. Dort musst du eine Zahlungsart haben, die den Text der von Checkout kommt (war bei PSP auch so) genau trifft (gleich ist). Dann wird es so zugewiesen wie eingestellt.

**Comment by 3d-printerstore** [comment]
Na dann gehe ich nochmals auf die Suche - dachte ich hätte genau das alles so eingestellt - aber danke für den Hinweis 👍

**Comment by 3d-printerstore** [comment]
@Alcpaone 
Kleine Frage,: hast du auf einmal auch eine zweite Abfrage "Zusätzliche Versandinformationen", bei der nochmal das Geschlecht ausgewählt werden muss?

**Comment by Alcpaone** [comment]
@3d-printerstore wo soll das sein? Checkout oder Shop?

**Comment by 3d-printerstore** [comment]
@Alcpaone 
checkout im shop
![image](https://github.com/pfpayments/jtl-5/assets/8004298/6916ddef-6e29-4ee5-8584-d37a1bfc1a71)

**Comment by Alcpaone** [comment]
@3d-printerstore haben wir nicht. Habt ihr das bei der Zahlungsart im Checkout eingestellt?

<img width="507" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/22252dd9-2674-49cf-b45a-15a9eea0e405">

**Comment by 3d-printerstore** [comment]
Nein, haben wir nicht eingestellt - kann ich auch nicht beeinflussen, was da erscheint - was für ein Template hast du?

**Comment by 3d-printerstore** [comment]
Denk, dass kommt von der Post selber:
![image](https://github.com/pfpayments/jtl-5/assets/8004298/4a048a57-24c4-415e-bbb6-1267941e668b)

Aber trotzdem komisch, dass du das nicht hast...

**Comment by Alcpaone** [comment]
@3d-printerstore mach doch einen eigenen Fall auf. Sonst geht dein Probelm unter und dieses mit der Strassennummer gleich auch.

Wir haben kein Default Template. Das hat aber nichts damit zu tun, da der angezeigte Inhalt vom Checkout geladen wird aus meiner Sicht.

**Comment by Alcpaone** [comment]
@edgaraswallee any update to this basic function?

**Comment by Alcpaone** [comment]
@edgaraswallee any news? 3 Weeks since the last release. There are several small bugs that would really be helpfull to be fixed. When will the next release be ready?

**Comment by thibault-mambour** [comment]
hi @Alcpaone , this issue should be fixed in the new release, could you please confirm ?

**Comment by Alcpaone** [comment]
Hi @thibault-mambour, yes, looks good so far with the first orders after the update.

**Comment by Alcpaone** [comment]
@thibault-mambour but there is some change, that looks strange.

Before Update in the email that checkout sends to customer (so we can track orders as long the sofware isn't perfect):
<img width="221" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/c574d2ec-ec59-45e1-a183-7a407bb81127">

after the update it looks a bit strange:

<img width="214" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/34ce4017-910b-4f82-b32b-7e6b08531274">

Error in the checkout form?

**Comment by Alcpaone** [comment]
I opened a new issue for the VAT description problem #36

**Comment by Alcpaone** [comment]
House number is now transfered with 1.0.23
