### ISSUE TITLE
French page doesnt show payment options

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#33]
Hello again
We are on 1.0.20 and when customer chooses french language, no payment methods are showed during checkout, the "postfinance" reel runs and runs and runs:
![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/d95fcac1-9f03-40fb-a0e8-f9d674c9b2e4)
French translations are done in the postfinace plugin and also all payment methods are translated.
Any idea someone?

**Comment by 3d-printerstore** [comment]
same here

**Comment by thibault-mambour** [comment]
hi @3d-printerstore @PAO1908CH , we will look very shortly into this, sorry for the inconvenience

**Comment by PAO1908CH** [comment]
The probleme is still here with 1.0.21:
![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/2989e71b-1ac2-46cd-b480-6330f3830531)
No checkout possible as payment methods don't show up on checkout page.

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , could you maybe share some reproduction steps and potentially your setup (if there are sensitive data, feel free to share it by email) ? 
On our side, if we clean cache after upgrading the plugin, if we use the french language we can see the payment methods

**Comment by PAO1908CH** [comment]
Hello again
Tried this out, cleared all the cache, same thing. English and German work without problems, I will send you the URL to our shop with PM, tell me if you need anything else from me.
Kind regards

**Comment by PAO1908CH** [comment]
How can I contact you?

**Comment by thibault-mambour** [comment]
hi @PAO1908CH, for this discussion you can send me an email directly to thibault.mambour@wallee.com

**Comment by 3d-printerstore** [comment]
same here - and only in French:
![image](https://github.com/pfpayments/jtl-5/assets/8004298/91a076b5-436e-49bd-9c49-1e1d9d8a0ef0)

**Comment by 3d-printerstore** [comment]
Furthermore is there another Problem with the Plug-in, as we have orders in the PostFinance Backend, which were paid with credit card, but not sent to the JTL Wawi - means the customer would never get his order, although he paid for it.
But I think, it's a french language problem as well.
![image](https://github.com/pfpayments/jtl-5/assets/8004298/ee3d82e5-383f-444a-a684-30278da7feeb)

**Comment by Alcpaone** [comment]
@PAO1908CH done? if so, please close the issue so we can all see the remaining tasks. Thank you!

**Comment by PAO1908CH** [comment]
The problem occurs only when Paypal Plugin from JTL is acitvated, they have a problem when somewhere in the french translation file a "-" exists. So it's not pfp related. As soon as I deactivated the Paypal Plugin, everything works. This problem occurs even when no Postfinance Plugin is installed. 

https://issues.jtl-software.de/issues?project=shop&query=SHOP-7474
