### ISSUE TITLE
1.0.21: Wrong UserID or Application Key / Plugin doesnt work

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#35]
Since 1.0.21 we get always wrong user or application key. With 1.0.20 plugin worked.
Regards

@edgaraswallee @andrewrowanwallee @sauliususoniswallee

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , it is working fine on our end. Do you have some reproductions steps on how to reproduce it ?

**Comment by PAO1908CH** [comment]
Indeed, retested right now and it works now, maybe there was a problem on the postfinance side. I will close this.
