### ISSUE TITLE
CRITICAL: Shop Voucher not working since 1.0.21

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#37]
@jbwallee @andrewrowanwallee @sauliususoniswallee @edgaraswallee

Since Release 1.0.21 Shop Voucher will not countet when transfering the Information from the shop basket to the checkout.

Example: Customer has to pay 100.-, Voucher 5% = 95.-  to pay in the shop -> Postfinance Checkout will ask for 100.- for payment.

Please fix this asap!

**Comment by thibault-mambour** [comment]
hi @Alcpaone , can you explain which plugin you are using for voucher and maybe share a bit more context ?

**Comment by Alcpaone** [comment]
@thibault-mambour **Thank you for your quick answer!**

We don't use any plugins for voucher. this is a build in solution of jtl shop 5 where you can generate vouchers for customers. We use them for many reasons like Newsletters, sales, abandonet cart and a lot more.

here you can finde more details about vouchers:

https://guide.jtl-software.com/en/jtl-shop/marketing-search-engine-optimisation/creating-coupons/

**Comment by Alcpaone** [comment]
@thibault-mambour 

it is doing some crazy shit now. I will send Patricius one example. You can yourself figure out what the system is doing now and please do it fast.

Customers has to pay 196.60 with a 5% voucher and will be charged in the checkout with 216.84 ?????????????

**Comment by thibault-mambour** [comment]
hi @Alcpaone did you check with plugin 1.0.23 ?

**Comment by Alcpaone** [comment]
@thibault-mambour 

Updated all shops to 1.0.23. Will see what happens with the next Orders with Voucher. Thank you for the quick fix!

**Comment by Alcpaone** [comment]
looks fixes since 1.0.23
