### ISSUE TITLE
SSH Access for Installation often not avaiable by hosters

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#4]
Is it possible that you implement the SSH command, that has to been executed, somehow into the installation script of the plugin? For example, all customers that have their JTL SHOP hosted by JTL, can not install the plugin, as JTL tells us:

SSH access is not possible for customers. In general, we do not execute any commands via SSH in customer hosting. Plugins should be provided by the developers as a complete package for installation via the shop. The ExtensionStore was also developed for this purpose.

So the plugin can not be installed as long as it's necessary to execute the command:

Run the install command
# Please go to /plugins/jtl_postfinancecheckout and run the command
composer install

We have also one shop that is hosted by another company, not JTL, and there it is also not possible to access SSH or run commands like the above.

Thanks and kind regards

**Comment by thibault-mambour** [comment]
Hi @PAO1908CH , we will see how we could make this happen. Would you have any additional request ?

**Comment by PAO1908CH** [comment]
Hello again
At the moment that's all, thank you.
Regards

thibault-mambour ***@***.***> schrieb am Do., 14. Dez. 2023,
13:31:

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , the release of today should fix the issue, could you please double check ?

**Comment by PAO1908CH** [comment]
Perfect, can confirm that, works without any console access now from version 1.06. Thank you!
