### ISSUE TITLE
New PostFinance Space Connecting Problem

### ISSUE THREAD

**Issue by 3d-printerstore** [pfpayments/jtl-5#41]
Hi there

As we have 2 webshops, we wanted to use this PlugIn as well for the 2nd webshop.
For this, we needed to open up a new "Space" in the Postfinance backend - all done, the new Space ID is integrated in the PlugIn, the payment methods are synchronized and I can make test orders with all methods - so all should be good, except that the TWINT payment is not transferred from the JTL shop to the JTL Wawi  - although the order status is "payed" in the JTL Shop, it does not say payed in the JTL Wawi - so it doesn't synchronize. Mastercard, Postfinancecard and Paypal work though.

Have you got an idea what the problem might be?

Br's
Ralph

**Comment by Alcpaone** [comment]
@3d-printerstore did you setup the Paymentmethodename in the second shop 1:1 as it is in Wawi? Wawi doesnt check any IDs, Wawi only checks if the name of the paymentmethod is the same as it is in Wawi. If it matches = payment done, else unpaid until you check and set to paid.

**Comment by 3d-printerstore** [comment]
Yes, the payment method names are the same in both shops - strangely all other payment methods work

**Comment by AmandaWallee** [comment]
Hi please contact checkout@postfinance.ch directly for your issue. 

Thanks!

**Comment by Alcpaone** [comment]
@3d-printerstore is your problem solved? Then please close the issue here. Thank you

**Comment by Alcpaone** [comment]
@3d-printerstore yes thats usual. So please close the issue. I can't do. Only admins and they don't have time....they have to fix the problems ;-)

**Comment by 3d-printerstore** [comment]
It’s closed, but could you or someone look at my other issue please?
“PHP Version 8.2 or higher #42”


Freundliche Grüsse / Salutations / Best regards

Ralph Borbeck
3D-PRINTERSTORE.CH

except ag
Weststrasse 15
CH - 8570 Weinfelden

+41 71 620 32 38
***@***.******@***.***>
https://3d-printerstore.ch<https://3d-printerstore.ch/>

Von: Alcpaone ***@***.***>
Gesendet: Montag, 13. Mai 2024 09:44
An: pfpayments/jtl-5 ***@***.***>
Cc: 3D Printerstore ***@***.***>; Mention ***@***.***>
Betreff: Re: [pfpayments/jtl-5] New PostFinance Space Connecting Problem (Issue #41)


@3d-printerstore<https://github.com/3d-printerstore> yes thats usual. So please close the issue. I can't do. Only admins and they don't have time....they have to fix the problems ;-)
