### ISSUE TITLE
Critical: Error message after payment cancellation / no more payment possible!

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#5]
After a payment cancelation (customer choose TWINT but then regret and goes back with the dedicated button to choose a different payment method) a strange / wrong / incomplete errors message appears:

"Die Zahlung ist für dieses Land oder diese Währung nicht möglich. Bitte verwenden Sie eine andere"

JTL Shop 5.2.4
PHP 8.1
Checkout Plugin Version 1.05

<img width="958" alt="Screenshot 2023-12-14 165802" src="https://github.com/pfpayments/jtl-5/assets/64169279/7f00200a-7d9f-44e2-9283-af39e88c0f53">

**Comment by thibault-mambour** [comment]
hi @Alcpaone , thank you for raising this, we'll investigate to see why you are getting this error message.

**Comment by Alcpaone** [comment]
@thibault-mambour fyi: also with the release of today (1.0.6) same error message.

<img width="959" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/545019a5-830f-4d87-ba97-861c736c9e11">

**Comment by Alcpaone** [comment]
@thibault-mambour later when? Please be more specific, as it is already 18.12.2023 / 15:52. Thank you

**Comment by PAO1908CH** [comment]
In 1.06 if I choose twint, and cancel the order, I get a white page and I get not redirected to the basket, the page that is opened is:

xy.com/postfinancecheckout-bezahlung-fehlgeschlagen

Regards

**Comment by thibault-mambour** [comment]
hi @Alcpaone , as it was only a problem of wording, it wasn't prioritised as we prefer to first handle functionality breaking bugs. But as it seems now it is breaking, we will have a look

**Comment by Alcpaone** [comment]
if customer try to choose a other payment methode after this message appears, you get the message the cart is emtpy.
Why is the cart lost?

<img width="960" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/969a0984-e0a5-455d-b1fe-fa4257584ee3">

**Comment by Alcpaone** [comment]
@thibault-mambour Plugin Version 1.0.10

Still same error

<img width="981" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/c5938516-c461-490c-ac43-0f2eade08882">

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 
will there be any new release today?

**PSP Shutdown in 9 days!** and we still don't have a working plugin.

**Comment by Alcpaone** [comment]
Hi @edgaraswallee, with Release 1.0.11 the situation has improved.
 
 Still wrong error message after payment abort but Cart is saved for a different payment method. Will test again to be shure.
Thank you!

<img width="961" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/308cec58-711f-42ec-a70b-b3e29b2e997e">

**Comment by edgaraswallee** [comment]
Hello, @Alcpaone error message text was not fixed in this release. We have internally created story for this and the message will be changed in next 3 days right after Christmas. It will be made by my colleagues. Thanks a lot for your effort and feedbacks it helps very much!

**Comment by Alcpaone** [comment]
@edgaraswallee it is now more then 10 days after christmas and 2 or 3 release later. The error message is still there / wrong and confusing customers.
