### ISSUE TITLE
Error 500 if customer chosse payment by invoice from checkout payment options

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#6]
if a customer selects the synchronized payment method of the checkout "on account", he gets an error 500
It is then no longer possible to change the payment method. You have to empty the shopping cart and start from the beginning.
Hardly any customer makes this effort

JTL Shop 5.2.4
PHP 8.1

**Comment by thibault-mambour** [comment]
hi @Alcpaone  , thank you for raising this, we'll investigate to see why you are getting this problem.
Just one question, do you expect a lot of merchant to use this option (this information might be helpful to put the correct priority to this issue vs others) ?

**Comment by Alcpaone** [comment]
Yes, this payment option is still very popular with customers. Of course, TWINT is No. 1 ahead of credit cards, but invoice is often used (when it works).

**Comment by thibault-mambour** [comment]
thank you for the feedback, we will tackle it accordingly

**Comment by thibault-mambour** [comment]
hi @Alcpaone , we are having issues reproducing the error on our end. Would it be possible to send a screen-recording or at least the steps required to reproduce this error ?

**Comment by Alcpaone** [comment]
@thibault-mambour there isnt a lot to show. Here one picture. After you choose payment method invoice and press "weiter" you get the error 500. In the picture is also the url ift that helps. 

<img width="531" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/5754dcb2-d685-4d30-8206-1a5d7bae46d3">

**Comment by Alcpaone** [comment]
@thibault-mambour btw: Patricius has all informations and you can also access to the system since month.

**Comment by thibault-mambour** [comment]
hi @Alcpaone thank you for the answer, I'll check internally

**Comment by Alcpaone** [comment]
@thibault-mambour 

Here is the error log for this in the front end. Complete url was replaced just here with XXX.

`Fatal error: Uncaught PostFinanceCheckout\Sdk\ApiException: Error 442 connecting to the API (https://checkout.postfinance.ch:443/api/transaction/update?spaceId=39035) : {"date":"2023-12-20T10:12:42.413Z","defaultMessage":"The unique ID on the line item is required.","id":"M_7tZhbZEqD9EluYUj2ZLTA_A7oaL85EWDAa4On3vAg (2023-12-20T10:12:42.413Z)","message":"The unique ID on the line item is required.","type":"DEVELOPER_ERROR"} in XXX/JTL-Shop/plugins/jtl_postfinancecheckout/vendor/postfinancecheckout/sdk/lib/ApiClient.php:504 Stack trace: #0 XXX/JTL-Shop/plugins/jtl_postfinancecheckout/vendor/postfinancecheckout/sdk/lib/Service/TransactionService.php(2068): PostFinanceCheckout\Sdk\ApiClient->callApi() #1 XXX/JTL-Shop/plugins/jtl_postfinancecheckout/vendor/postfinancecheckout/sdk/lib/Service/TransactionService.php(2000): PostFinanceCheckout\Sdk\Service\TransactionService->updateWithHttpInfo() #2 XXX/JTL-Shop/plugins/jtl_postfinancecheckout/Services/PostFinanceCheckoutTransactionService.php(133): PostFinanceCheckout\Sdk\Service\TransactionService->update() #3 XXX/JTL-Shop/plugins/jtl_postfinancecheckout/frontend/Handler.php(103): Plugin\jtl_postfinancecheckout\Services\PostFinanceCheckoutTransactionService->updateTransaction() #4 XXX/JTL-Shop/plugins/jtl_postfinancecheckout/frontend/Handler.php(195): Plugin\jtl_postfinancecheckout\frontend\Handler->handleTransaction() #5 XXX/JTL-Shop/includes/src/Events/Dispatcher.php(82): Plugin\jtl_postfinancecheckout\frontend\Handler->contentUpdate() #6 XXX/JTL-Shop/includes/src/Plugin/HookManager.php(108): JTL\Events\Dispatcher->fire() #7 XXX/JTL-Shop/includes/defines.php(318): JTL\Plugin\HookManager->executeHook() #8 XXX/JTL-Shop/includes/src/Smarty/JTLSmarty.php(204): executeHook() #9 XXX/JTL-Shop/includes/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_filterhandler.php(63): JTL\Smarty\JTLSmarty->outputFilter() #10 XXX/JTL-Shop/includes/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(255): Smarty_Internal_Runtime_FilterHandler->runFilter() #11 XXX/JTL-Shop/includes/src/Smarty/JTLSmartyTemplateClass.php(59): Smarty_Internal_Template->render() #12 XXX/JTL-Shop/includes/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): JTL\Smarty\JTLSmartyTemplateClass->render() #13 XXX/JTL-Shop/includes/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute() #14 XXX/JTL-Shop/includes/src/Smarty/JTLSmarty.php(344): Smarty_Internal_TemplateBase->fetch() #15 XXX/JTL-Shop/includes/src/Router/Controller/CheckoutController.php(338): JTL\Smarty\JTLSmarty->getResponse() #16 XXX/JTL-Shop/includes/src/Router/Controller/DefaultController.php(114): JTL\Router\Controller\CheckoutController->getResponse() #17 XXX/JTL-Shop/includes/src/Router/Router.php(684): JTL\Router\Controller\DefaultController->getResponse() #18 XXX/JTL-Shop/includes/src/Shop.php(472): JTL\Router\Router->dispatch() #19 XXX/JTL-Shop/index.php(7): JTL\Shop::dispatch() #20 {main} thrown in XXX/JTL-Shop/plugins/jtl_postfinancecheckout/vendor/postfinancecheckout/sdk/lib/ApiClient.php on line 504`

**Comment by Alcpaone** [comment]
@thibault-mambour 
Plugin Version 1.0.10
stimm same Error 500

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 
will there be any new release today?

**PSP Shutdown in 9 days!** and we still don't have a working plugin.

**Comment by edgaraswallee** [comment]
Hello, @Alcpaone , I'm currently working on one of your created issues. 
When I will find a solution, I will release asap. 
New release will be made tonight or tomorrow, depending on when I'll find a solution for it. 
Thanks for understanding.

**Comment by edgaraswallee** [comment]
Good morning, @Alcpaone , release has been made. Can you please check and provide a feedback?

**Comment by Alcpaone** [comment]
Hi @edgaraswallee looks good until now (no error 500, payment mask starts), need to search good customer informations to do a complete test. Welcome if you can provide me the sample informations.

**Comment by Alcpaone** [comment]
@edgaraswallee until now it looks good. Well done. Thank you
