### ISSUE TITLE
Cart blocked after paymentmethod change / no order possible

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#8]
Customer fills shopping cart, goes through to payment, let's say with TWINT, and then decides to go back and change the payment method, the shopping cart is no longer available.

If you add the product(s) again and want to pay, the same error message always appears
<img width="970" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/f0e42b11-06d8-4f57-a269-95f5eedff311">

No matter what you do, start again, as soon as you select the button Order with obligation to pay the above message appears again and again.

JTL Shop  5.2.4
PHP8.1

**Comment by Alcpaone** [comment]
@thibault-mambour fyi: also here no changes after update to 1.0.6, 
<img width="945" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/60f0f40e-a015-42aa-92c4-81e2844613ff">

**Comment by Alcpaone** [comment]
**Plugin Version 1.0.9**
Still same issue, just for documentation purpose but important to fix
<img width="967" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/0a3074f4-3ccd-4744-bbdc-78d090619273">

**Comment by thibault-mambour** [comment]
hi @Alcpaone , we would like to apologise for the time to look at this bug, we will get to it but we are working first to have full wawi support as well as high impact bug touching key functionalities

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 
It's sad to see that problems could have been tackled without pressure since August 2023 and now everyone is under so much stress before Christmas. 

**PSP will be shut down in 10 days!** 

_### Thanks for the support and the upcoming release today!_

**Comment by Alcpaone** [comment]
looks like it is done since a few releases.
