### ISSUE TITLE
Critical: 1.06: Orders can be placed successfully, payement done, but they are not written into JTL SHOP Database

### ISSUE THREAD

**Issue by PAO1908CH** [pfpayments/jtl-5#9]
We found out today, that the orders that are placed with 1.06 version, are not written into the jtl shop database and basically, if you don't look at postfinance checkout, you will never see those orders. We were wondered that no orders are coming in anymore those days. The payment has been processed successfully, so we don't talk about orders, that are not paid. That's critical as we got already a few mails from customers that placed orders and we didn't know, that they ordered. That should be fixed with first priority!

Payment before order is set to YES.
Guest checkout and registered checkout is affected.
Checked with TWINT and CreditCard payments over postfinance

The order number the shop gives after payment is successfull is not like the order numbers we give normally:

![grafik](https://github.com/pfpayments/jtl-5/assets/149598982/22cc406c-9d34-49e7-8eaf-5d1a11e34802)

we normally have something like 11xxx

of course, as there is no order in JTL Shop, customers also don't get any confirmation mail.

**Comment by thibault-mambour** [comment]
hi @PAO1908CH  it was reproduced on our side, we are working on a fix

**Comment by PAO1908CH** [comment]
Both, the shop doesnt know, that there was a order, so the order is not in the shop, and then, of course also not transfered to the wawi.

**Comment by PAO1908CH** [comment]
> hi @PAO1908CH it was reproduced on our side, we are working on a fix

perfect, thank you.

**Comment by thibault-mambour** [comment]
hi @PAO1908CH , the hotfix should tackle this issue, could you confirm it ?

**Comment by PAO1908CH** [comment]
Affirm, works here! thanks a lot for this fast fix!
kind regards

**Comment by PAO1908CH** [comment]
> hi @PAO1908CH , the hotfix should tackle this issue, could you confirm it ?

Unfortunately, the error that orders are placed into jtl shop even when payment is not successfull is back now with 1.07...
So when I choose a payment method, and cancel it, order is stored into the system and also into the WAWI.
